// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pggen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO loyalty_cards (user_id)
VALUES ($1)
RETURNING id, user_id, balance, created_at, updated_at, is_blocked
`

func (q *Queries) Create(ctx context.Context, userID uuid.UUID) (LoyaltyCard, error) {
	row := q.db.QueryRowContext(ctx, create, userID)
	var i LoyaltyCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBlocked,
	)
	return i, err
}

const delete = `-- name: Delete :one
DELETE FROM loyalty_cards
WHERE user_id = $1
RETURNING id, user_id, balance, created_at, updated_at, is_blocked
`

func (q *Queries) Delete(ctx context.Context, userID uuid.UUID) (LoyaltyCard, error) {
	row := q.db.QueryRowContext(ctx, delete, userID)
	var i LoyaltyCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBlocked,
	)
	return i, err
}

const findByUserID = `-- name: FindByUserID :one
SELECT id, user_id, balance, created_at, updated_at, is_blocked
FROM loyalty_cards
WHERE user_id = $1
`

func (q *Queries) FindByUserID(ctx context.Context, userID uuid.UUID) (LoyaltyCard, error) {
	row := q.db.QueryRowContext(ctx, findByUserID, userID)
	var i LoyaltyCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBlocked,
	)
	return i, err
}

const updateBalance = `-- name: UpdateBalance :one
UPDATE loyalty_cards
SET balance = $1, updated_at = NOW()
WHERE user_id = $2
RETURNING id, user_id, balance, created_at, updated_at, is_blocked
`

type UpdateBalanceParams struct {
	Balance sql.NullString
	UserID  uuid.UUID
}

func (q *Queries) UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (LoyaltyCard, error) {
	row := q.db.QueryRowContext(ctx, updateBalance, arg.Balance, arg.UserID)
	var i LoyaltyCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBlocked,
	)
	return i, err
}

const updateIsBlocked = `-- name: UpdateIsBlocked :one
UPDATE loyalty_cards
SET is_blocked = $1, updated_at = NOW()
WHERE user_id = $2
RETURNING id, user_id, balance, created_at, updated_at, is_blocked
`

type UpdateIsBlockedParams struct {
	IsBlocked bool
	UserID    uuid.UUID
}

func (q *Queries) UpdateIsBlocked(ctx context.Context, arg UpdateIsBlockedParams) (LoyaltyCard, error) {
	row := q.db.QueryRowContext(ctx, updateIsBlocked, arg.IsBlocked, arg.UserID)
	var i LoyaltyCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBlocked,
	)
	return i, err
}
