// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// APIV1LoyaltyBalancePatch implements PATCH /api/v1/loyalty/balance operation.
	//
	// Method to update loyalty card balance.
	//
	// PATCH /api/v1/loyalty/balance
	APIV1LoyaltyBalancePatch(ctx context.Context, req *UpdateBalanceRequest) (APIV1LoyaltyBalancePatchRes, error)
	// APIV1LoyaltyCreatePost implements POST /api/v1/loyalty/create operation.
	//
	// Creates a new loyalty card for new user.
	//
	// POST /api/v1/loyalty/create
	APIV1LoyaltyCreatePost(ctx context.Context, req *CreateLoyaltyCardRequest) (APIV1LoyaltyCreatePostRes, error)
	// APIV1LoyaltyDeleteDelete implements DELETE /api/v1/loyalty/delete operation.
	//
	// Method to delete user's loyalty card.
	//
	// DELETE /api/v1/loyalty/delete
	APIV1LoyaltyDeleteDelete(ctx context.Context, req *DeleteLoyaltyCardRequest) (APIV1LoyaltyDeleteDeleteRes, error)
	// APIV1LoyaltyGet implements GET /api/v1/loyalty operation.
	//
	// Method to get user's loyalty card.
	//
	// GET /api/v1/loyalty
	APIV1LoyaltyGet(ctx context.Context, params APIV1LoyaltyGetParams) (APIV1LoyaltyGetRes, error)
	// APIV1LoyaltyIsBlockedPatch implements PATCH /api/v1/loyalty/is_blocked operation.
	//
	// Method to block or unblock loyalty card.
	//
	// PATCH /api/v1/loyalty/is_blocked
	APIV1LoyaltyIsBlockedPatch(ctx context.Context, req *UpdateIsBlockRequest) (APIV1LoyaltyIsBlockedPatchRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
