// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// APIV1LoyaltyBalancePatch implements PATCH /api/v1/loyalty/balance operation.
//
// Method to update loyalty card balance.
//
// PATCH /api/v1/loyalty/balance
func (UnimplementedHandler) APIV1LoyaltyBalancePatch(ctx context.Context, req *UpdateBalanceRequest) (r APIV1LoyaltyBalancePatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1LoyaltyCreatePost implements POST /api/v1/loyalty/create operation.
//
// Creates a new loyalty card for new user.
//
// POST /api/v1/loyalty/create
func (UnimplementedHandler) APIV1LoyaltyCreatePost(ctx context.Context, req *CreateLoyaltyCardRequest) (r APIV1LoyaltyCreatePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1LoyaltyDeleteDelete implements DELETE /api/v1/loyalty/delete operation.
//
// Method to delete user's loyalty card.
//
// DELETE /api/v1/loyalty/delete
func (UnimplementedHandler) APIV1LoyaltyDeleteDelete(ctx context.Context, req *DeleteLoyaltyCardRequest) (r APIV1LoyaltyDeleteDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1LoyaltyGet implements GET /api/v1/loyalty operation.
//
// Method to get user's loyalty card.
//
// GET /api/v1/loyalty
func (UnimplementedHandler) APIV1LoyaltyGet(ctx context.Context, params APIV1LoyaltyGetParams) (r APIV1LoyaltyGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// APIV1LoyaltyIsBlockedPatch implements PATCH /api/v1/loyalty/is_blocked operation.
//
// Method to block or unblock loyalty card.
//
// PATCH /api/v1/loyalty/is_blocked
func (UnimplementedHandler) APIV1LoyaltyIsBlockedPatch(ctx context.Context, req *UpdateIsBlockRequest) (r APIV1LoyaltyIsBlockedPatchRes, _ error) {
	return r, ht.ErrNotImplemented
}
