// Code generated by ogen, DO NOT EDIT.

package httpgen

// OperationName is the ogen operation name
type OperationName = string

const (
	APIV1LoyaltyBalancePatchOperation   OperationName = "APIV1LoyaltyBalancePatch"
	APIV1LoyaltyCreatePostOperation     OperationName = "APIV1LoyaltyCreatePost"
	APIV1LoyaltyDeleteDeleteOperation   OperationName = "APIV1LoyaltyDeleteDelete"
	APIV1LoyaltyGetOperation            OperationName = "APIV1LoyaltyGet"
	APIV1LoyaltyIsBlockedPatchOperation OperationName = "APIV1LoyaltyIsBlockedPatch"
)
