// Code generated by ogen, DO NOT EDIT.
package httpgen

type APIV1LoyaltyBalancePatchRes interface {
	aPIV1LoyaltyBalancePatchRes()
}

type APIV1LoyaltyCreatePostRes interface {
	aPIV1LoyaltyCreatePostRes()
}

type APIV1LoyaltyDeleteDeleteRes interface {
	aPIV1LoyaltyDeleteDeleteRes()
}

type APIV1LoyaltyGetRes interface {
	aPIV1LoyaltyGetRes()
}

type APIV1LoyaltyIsBlockedPatchRes interface {
	aPIV1LoyaltyIsBlockedPatchRes()
}
