// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

type APIV1LoyaltyBalancePatchBadRequest ErrorResponse

func (*APIV1LoyaltyBalancePatchBadRequest) aPIV1LoyaltyBalancePatchRes() {}

type APIV1LoyaltyBalancePatchGatewayTimeout ErrorResponse

func (*APIV1LoyaltyBalancePatchGatewayTimeout) aPIV1LoyaltyBalancePatchRes() {}

type APIV1LoyaltyBalancePatchInternalServerError ErrorResponse

func (*APIV1LoyaltyBalancePatchInternalServerError) aPIV1LoyaltyBalancePatchRes() {}

type APIV1LoyaltyBalancePatchNotFound ErrorResponse

func (*APIV1LoyaltyBalancePatchNotFound) aPIV1LoyaltyBalancePatchRes() {}

type APIV1LoyaltyCreatePostBadRequest ErrorResponse

func (*APIV1LoyaltyCreatePostBadRequest) aPIV1LoyaltyCreatePostRes() {}

type APIV1LoyaltyCreatePostGatewayTimeout ErrorResponse

func (*APIV1LoyaltyCreatePostGatewayTimeout) aPIV1LoyaltyCreatePostRes() {}

type APIV1LoyaltyCreatePostInternalServerError ErrorResponse

func (*APIV1LoyaltyCreatePostInternalServerError) aPIV1LoyaltyCreatePostRes() {}

type APIV1LoyaltyDeleteDeleteBadRequest ErrorResponse

func (*APIV1LoyaltyDeleteDeleteBadRequest) aPIV1LoyaltyDeleteDeleteRes() {}

type APIV1LoyaltyDeleteDeleteGatewayTimeout ErrorResponse

func (*APIV1LoyaltyDeleteDeleteGatewayTimeout) aPIV1LoyaltyDeleteDeleteRes() {}

type APIV1LoyaltyDeleteDeleteInternalServerError ErrorResponse

func (*APIV1LoyaltyDeleteDeleteInternalServerError) aPIV1LoyaltyDeleteDeleteRes() {}

// APIV1LoyaltyDeleteDeleteNoContent is response for APIV1LoyaltyDeleteDelete operation.
type APIV1LoyaltyDeleteDeleteNoContent struct{}

func (*APIV1LoyaltyDeleteDeleteNoContent) aPIV1LoyaltyDeleteDeleteRes() {}

type APIV1LoyaltyDeleteDeleteNotFound ErrorResponse

func (*APIV1LoyaltyDeleteDeleteNotFound) aPIV1LoyaltyDeleteDeleteRes() {}

type APIV1LoyaltyGetBadRequest ErrorResponse

func (*APIV1LoyaltyGetBadRequest) aPIV1LoyaltyGetRes() {}

type APIV1LoyaltyGetGatewayTimeout ErrorResponse

func (*APIV1LoyaltyGetGatewayTimeout) aPIV1LoyaltyGetRes() {}

type APIV1LoyaltyGetInternalServerError ErrorResponse

func (*APIV1LoyaltyGetInternalServerError) aPIV1LoyaltyGetRes() {}

type APIV1LoyaltyGetNotFound ErrorResponse

func (*APIV1LoyaltyGetNotFound) aPIV1LoyaltyGetRes() {}

type APIV1LoyaltyIsBlockedPatchBadRequest ErrorResponse

func (*APIV1LoyaltyIsBlockedPatchBadRequest) aPIV1LoyaltyIsBlockedPatchRes() {}

type APIV1LoyaltyIsBlockedPatchGatewayTimeout ErrorResponse

func (*APIV1LoyaltyIsBlockedPatchGatewayTimeout) aPIV1LoyaltyIsBlockedPatchRes() {}

type APIV1LoyaltyIsBlockedPatchInternalServerError ErrorResponse

func (*APIV1LoyaltyIsBlockedPatchInternalServerError) aPIV1LoyaltyIsBlockedPatchRes() {}

type APIV1LoyaltyIsBlockedPatchNotFound ErrorResponse

func (*APIV1LoyaltyIsBlockedPatchNotFound) aPIV1LoyaltyIsBlockedPatchRes() {}

// Ref: #/components/schemas/CreateLoyaltyCardRequest
type CreateLoyaltyCardRequest struct {
	UserID uuid.UUID `json:"user_id"`
}

// GetUserID returns the value of UserID.
func (s *CreateLoyaltyCardRequest) GetUserID() uuid.UUID {
	return s.UserID
}

// SetUserID sets the value of UserID.
func (s *CreateLoyaltyCardRequest) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// Ref: #/components/schemas/DeleteLoyaltyCardRequest
type DeleteLoyaltyCardRequest struct {
	UserID uuid.UUID `json:"user_id"`
}

// GetUserID returns the value of UserID.
func (s *DeleteLoyaltyCardRequest) GetUserID() uuid.UUID {
	return s.UserID
}

// SetUserID sets the value of UserID.
func (s *DeleteLoyaltyCardRequest) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() int {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val int) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/LoyaltyCard
type LoyaltyCard struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Balance   float64   `json:"balance"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	IsBlocked bool      `json:"is_blocked"`
}

// GetID returns the value of ID.
func (s *LoyaltyCard) GetID() uuid.UUID {
	return s.ID
}

// GetUserID returns the value of UserID.
func (s *LoyaltyCard) GetUserID() uuid.UUID {
	return s.UserID
}

// GetBalance returns the value of Balance.
func (s *LoyaltyCard) GetBalance() float64 {
	return s.Balance
}

// GetCreatedAt returns the value of CreatedAt.
func (s *LoyaltyCard) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *LoyaltyCard) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// GetIsBlocked returns the value of IsBlocked.
func (s *LoyaltyCard) GetIsBlocked() bool {
	return s.IsBlocked
}

// SetID sets the value of ID.
func (s *LoyaltyCard) SetID(val uuid.UUID) {
	s.ID = val
}

// SetUserID sets the value of UserID.
func (s *LoyaltyCard) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetBalance sets the value of Balance.
func (s *LoyaltyCard) SetBalance(val float64) {
	s.Balance = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *LoyaltyCard) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *LoyaltyCard) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// SetIsBlocked sets the value of IsBlocked.
func (s *LoyaltyCard) SetIsBlocked(val bool) {
	s.IsBlocked = val
}

func (*LoyaltyCard) aPIV1LoyaltyBalancePatchRes()   {}
func (*LoyaltyCard) aPIV1LoyaltyCreatePostRes()     {}
func (*LoyaltyCard) aPIV1LoyaltyGetRes()            {}
func (*LoyaltyCard) aPIV1LoyaltyIsBlockedPatchRes() {}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/UpdateBalanceRequest
type UpdateBalanceRequest struct {
	// Amount must be > 0.0.
	Amount float64                  `json:"amount"`
	UserID uuid.UUID                `json:"user_id"`
	Mode   UpdateBalanceRequestMode `json:"mode"`
}

// GetAmount returns the value of Amount.
func (s *UpdateBalanceRequest) GetAmount() float64 {
	return s.Amount
}

// GetUserID returns the value of UserID.
func (s *UpdateBalanceRequest) GetUserID() uuid.UUID {
	return s.UserID
}

// GetMode returns the value of Mode.
func (s *UpdateBalanceRequest) GetMode() UpdateBalanceRequestMode {
	return s.Mode
}

// SetAmount sets the value of Amount.
func (s *UpdateBalanceRequest) SetAmount(val float64) {
	s.Amount = val
}

// SetUserID sets the value of UserID.
func (s *UpdateBalanceRequest) SetUserID(val uuid.UUID) {
	s.UserID = val
}

// SetMode sets the value of Mode.
func (s *UpdateBalanceRequest) SetMode(val UpdateBalanceRequestMode) {
	s.Mode = val
}

type UpdateBalanceRequestMode string

const (
	UpdateBalanceRequestModeAdd      UpdateBalanceRequestMode = "add"
	UpdateBalanceRequestModeWithdraw UpdateBalanceRequestMode = "withdraw"
)

// AllValues returns all UpdateBalanceRequestMode values.
func (UpdateBalanceRequestMode) AllValues() []UpdateBalanceRequestMode {
	return []UpdateBalanceRequestMode{
		UpdateBalanceRequestModeAdd,
		UpdateBalanceRequestModeWithdraw,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UpdateBalanceRequestMode) MarshalText() ([]byte, error) {
	switch s {
	case UpdateBalanceRequestModeAdd:
		return []byte(s), nil
	case UpdateBalanceRequestModeWithdraw:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UpdateBalanceRequestMode) UnmarshalText(data []byte) error {
	switch UpdateBalanceRequestMode(data) {
	case UpdateBalanceRequestModeAdd:
		*s = UpdateBalanceRequestModeAdd
		return nil
	case UpdateBalanceRequestModeWithdraw:
		*s = UpdateBalanceRequestModeWithdraw
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/UpdateIsBlockRequest
type UpdateIsBlockRequest struct {
	IsBlocked bool      `json:"is_blocked"`
	UserID    uuid.UUID `json:"user_id"`
}

// GetIsBlocked returns the value of IsBlocked.
func (s *UpdateIsBlockRequest) GetIsBlocked() bool {
	return s.IsBlocked
}

// GetUserID returns the value of UserID.
func (s *UpdateIsBlockRequest) GetUserID() uuid.UUID {
	return s.UserID
}

// SetIsBlocked sets the value of IsBlocked.
func (s *UpdateIsBlockRequest) SetIsBlocked(val bool) {
	s.IsBlocked = val
}

// SetUserID sets the value of UserID.
func (s *UpdateIsBlockRequest) SetUserID(val uuid.UUID) {
	s.UserID = val
}
